// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/SpiderAuthorizedPayload.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SpiderAuthorizedPayload.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SpiderAuthorizedPayload_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpiderAuthorizedPayload_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Proto_2fSpiderAuthorizedPayload_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Proto_2fSpiderAuthorizedPayload_2eproto() {
  protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Proto/SpiderAuthorizedPayload.proto");
  GOOGLE_CHECK(file != NULL);
  SpiderAuthorizedPayload_descriptor_ = file->message_type(0);
  static const int SpiderAuthorizedPayload_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpiderAuthorizedPayload, key_),
  };
  SpiderAuthorizedPayload_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SpiderAuthorizedPayload_descriptor_,
      SpiderAuthorizedPayload::internal_default_instance(),
      SpiderAuthorizedPayload_offsets_,
      -1,
      -1,
      -1,
      sizeof(SpiderAuthorizedPayload),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpiderAuthorizedPayload, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Proto_2fSpiderAuthorizedPayload_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SpiderAuthorizedPayload_descriptor_, SpiderAuthorizedPayload::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Proto_2fSpiderAuthorizedPayload_2eproto() {
  SpiderAuthorizedPayload_default_instance_.Shutdown();
  delete SpiderAuthorizedPayload_reflection_;
}

void protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  SpiderAuthorizedPayload_default_instance_.DefaultConstruct();
  SpiderAuthorizedPayload_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto_once_);
void protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto_once_,
                 &protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto_impl);
}
void protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n#Proto/SpiderAuthorizedPayload.proto\"&\n"
    "\027SpiderAuthorizedPayload\022\013\n\003Key\030\001 \001(\014b\006p"
    "roto3", 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Proto/SpiderAuthorizedPayload.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Proto_2fSpiderAuthorizedPayload_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto_once_);
void protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto_once_,
                 &protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Proto_2fSpiderAuthorizedPayload_2eproto {
  StaticDescriptorInitializer_Proto_2fSpiderAuthorizedPayload_2eproto() {
    protobuf_AddDesc_Proto_2fSpiderAuthorizedPayload_2eproto();
  }
} static_descriptor_initializer_Proto_2fSpiderAuthorizedPayload_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpiderAuthorizedPayload::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpiderAuthorizedPayload::SpiderAuthorizedPayload()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:SpiderAuthorizedPayload)
}

void SpiderAuthorizedPayload::InitAsDefaultInstance() {
}

SpiderAuthorizedPayload::SpiderAuthorizedPayload(const SpiderAuthorizedPayload& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SpiderAuthorizedPayload)
}

void SpiderAuthorizedPayload::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

SpiderAuthorizedPayload::~SpiderAuthorizedPayload() {
  // @@protoc_insertion_point(destructor:SpiderAuthorizedPayload)
  SharedDtor();
}

void SpiderAuthorizedPayload::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SpiderAuthorizedPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpiderAuthorizedPayload::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpiderAuthorizedPayload_descriptor_;
}

const SpiderAuthorizedPayload& SpiderAuthorizedPayload::default_instance() {
  protobuf_InitDefaults_Proto_2fSpiderAuthorizedPayload_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SpiderAuthorizedPayload> SpiderAuthorizedPayload_default_instance_;

SpiderAuthorizedPayload* SpiderAuthorizedPayload::New(::google::protobuf::Arena* arena) const {
  SpiderAuthorizedPayload* n = new SpiderAuthorizedPayload;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SpiderAuthorizedPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:SpiderAuthorizedPayload)
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool SpiderAuthorizedPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SpiderAuthorizedPayload)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes Key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SpiderAuthorizedPayload)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SpiderAuthorizedPayload)
  return false;
#undef DO_
}

void SpiderAuthorizedPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SpiderAuthorizedPayload)
  // optional bytes Key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->key(), output);
  }

  // @@protoc_insertion_point(serialize_end:SpiderAuthorizedPayload)
}

::google::protobuf::uint8* SpiderAuthorizedPayload::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:SpiderAuthorizedPayload)
  // optional bytes Key = 1;
  if (this->key().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SpiderAuthorizedPayload)
  return target;
}

size_t SpiderAuthorizedPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SpiderAuthorizedPayload)
  size_t total_size = 0;

  // optional bytes Key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpiderAuthorizedPayload::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SpiderAuthorizedPayload)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SpiderAuthorizedPayload* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpiderAuthorizedPayload>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SpiderAuthorizedPayload)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SpiderAuthorizedPayload)
    UnsafeMergeFrom(*source);
  }
}

void SpiderAuthorizedPayload::MergeFrom(const SpiderAuthorizedPayload& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SpiderAuthorizedPayload)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void SpiderAuthorizedPayload::UnsafeMergeFrom(const SpiderAuthorizedPayload& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void SpiderAuthorizedPayload::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SpiderAuthorizedPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpiderAuthorizedPayload::CopyFrom(const SpiderAuthorizedPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SpiderAuthorizedPayload)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool SpiderAuthorizedPayload::IsInitialized() const {

  return true;
}

void SpiderAuthorizedPayload::Swap(SpiderAuthorizedPayload* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpiderAuthorizedPayload::InternalSwap(SpiderAuthorizedPayload* other) {
  key_.Swap(&other->key_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SpiderAuthorizedPayload::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpiderAuthorizedPayload_descriptor_;
  metadata.reflection = SpiderAuthorizedPayload_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SpiderAuthorizedPayload

// optional bytes Key = 1;
void SpiderAuthorizedPayload::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SpiderAuthorizedPayload::key() const {
  // @@protoc_insertion_point(field_get:SpiderAuthorizedPayload.Key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SpiderAuthorizedPayload::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SpiderAuthorizedPayload.Key)
}
void SpiderAuthorizedPayload::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SpiderAuthorizedPayload.Key)
}
void SpiderAuthorizedPayload::set_key(const void* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SpiderAuthorizedPayload.Key)
}
::std::string* SpiderAuthorizedPayload::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:SpiderAuthorizedPayload.Key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SpiderAuthorizedPayload::release_key() {
  // @@protoc_insertion_point(field_release:SpiderAuthorizedPayload.Key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SpiderAuthorizedPayload::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:SpiderAuthorizedPayload.Key)
}

inline const SpiderAuthorizedPayload* SpiderAuthorizedPayload::internal_default_instance() {
  return &SpiderAuthorizedPayload_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
