// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/SpiderAuthenticationPayload.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SpiderAuthenticationPayload.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SpiderAuthenticationPayload_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpiderAuthenticationPayload_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Proto_2fSpiderAuthenticationPayload_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Proto_2fSpiderAuthenticationPayload_2eproto() {
  protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Proto/SpiderAuthenticationPayload.proto");
  GOOGLE_CHECK(file != NULL);
  SpiderAuthenticationPayload_descriptor_ = file->message_type(0);
  static const int SpiderAuthenticationPayload_offsets_[1] = {
  };
  SpiderAuthenticationPayload_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SpiderAuthenticationPayload_descriptor_,
      SpiderAuthenticationPayload::internal_default_instance(),
      SpiderAuthenticationPayload_offsets_,
      -1,
      -1,
      -1,
      sizeof(SpiderAuthenticationPayload),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpiderAuthenticationPayload, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Proto_2fSpiderAuthenticationPayload_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SpiderAuthenticationPayload_descriptor_, SpiderAuthenticationPayload::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Proto_2fSpiderAuthenticationPayload_2eproto() {
  SpiderAuthenticationPayload_default_instance_.Shutdown();
  delete SpiderAuthenticationPayload_reflection_;
}

void protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  SpiderAuthenticationPayload_default_instance_.DefaultConstruct();
  SpiderAuthenticationPayload_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto_once_);
void protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto_once_,
                 &protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto_impl);
}
void protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\'Proto/SpiderAuthenticationPayload.prot"
    "o\"\035\n\033SpiderAuthenticationPayloadb\006proto3", 80);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Proto/SpiderAuthenticationPayload.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Proto_2fSpiderAuthenticationPayload_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto_once_);
void protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto_once_,
                 &protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Proto_2fSpiderAuthenticationPayload_2eproto {
  StaticDescriptorInitializer_Proto_2fSpiderAuthenticationPayload_2eproto() {
    protobuf_AddDesc_Proto_2fSpiderAuthenticationPayload_2eproto();
  }
} static_descriptor_initializer_Proto_2fSpiderAuthenticationPayload_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpiderAuthenticationPayload::SpiderAuthenticationPayload()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:SpiderAuthenticationPayload)
}

void SpiderAuthenticationPayload::InitAsDefaultInstance() {
}

SpiderAuthenticationPayload::SpiderAuthenticationPayload(const SpiderAuthenticationPayload& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SpiderAuthenticationPayload)
}

void SpiderAuthenticationPayload::SharedCtor() {
  _cached_size_ = 0;
}

SpiderAuthenticationPayload::~SpiderAuthenticationPayload() {
  // @@protoc_insertion_point(destructor:SpiderAuthenticationPayload)
  SharedDtor();
}

void SpiderAuthenticationPayload::SharedDtor() {
}

void SpiderAuthenticationPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpiderAuthenticationPayload::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpiderAuthenticationPayload_descriptor_;
}

const SpiderAuthenticationPayload& SpiderAuthenticationPayload::default_instance() {
  protobuf_InitDefaults_Proto_2fSpiderAuthenticationPayload_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SpiderAuthenticationPayload> SpiderAuthenticationPayload_default_instance_;

SpiderAuthenticationPayload* SpiderAuthenticationPayload::New(::google::protobuf::Arena* arena) const {
  SpiderAuthenticationPayload* n = new SpiderAuthenticationPayload;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SpiderAuthenticationPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:SpiderAuthenticationPayload)
}

bool SpiderAuthenticationPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SpiderAuthenticationPayload)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:SpiderAuthenticationPayload)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SpiderAuthenticationPayload)
  return false;
#undef DO_
}

void SpiderAuthenticationPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SpiderAuthenticationPayload)
  // @@protoc_insertion_point(serialize_end:SpiderAuthenticationPayload)
}

::google::protobuf::uint8* SpiderAuthenticationPayload::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:SpiderAuthenticationPayload)
  // @@protoc_insertion_point(serialize_to_array_end:SpiderAuthenticationPayload)
  return target;
}

size_t SpiderAuthenticationPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SpiderAuthenticationPayload)
  size_t total_size = 0;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpiderAuthenticationPayload::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SpiderAuthenticationPayload)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SpiderAuthenticationPayload* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpiderAuthenticationPayload>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SpiderAuthenticationPayload)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SpiderAuthenticationPayload)
    UnsafeMergeFrom(*source);
  }
}

void SpiderAuthenticationPayload::MergeFrom(const SpiderAuthenticationPayload& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SpiderAuthenticationPayload)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void SpiderAuthenticationPayload::UnsafeMergeFrom(const SpiderAuthenticationPayload& from) {
  GOOGLE_DCHECK(&from != this);
}

void SpiderAuthenticationPayload::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SpiderAuthenticationPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpiderAuthenticationPayload::CopyFrom(const SpiderAuthenticationPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SpiderAuthenticationPayload)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool SpiderAuthenticationPayload::IsInitialized() const {

  return true;
}

void SpiderAuthenticationPayload::Swap(SpiderAuthenticationPayload* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpiderAuthenticationPayload::InternalSwap(SpiderAuthenticationPayload* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SpiderAuthenticationPayload::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpiderAuthenticationPayload_descriptor_;
  metadata.reflection = SpiderAuthenticationPayload_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SpiderAuthenticationPayload

inline const SpiderAuthenticationPayload* SpiderAuthenticationPayload::internal_default_instance() {
  return &SpiderAuthenticationPayload_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
