// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/GetMouselogCommandResponse.proto

#ifndef PROTOBUF_Proto_2fGetMouselogCommandResponse_2eproto__INCLUDED
#define PROTOBUF_Proto_2fGetMouselogCommandResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "SpiderMouseEvent.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Proto_2fGetMouselogCommandResponse_2eproto();
void protobuf_InitDefaults_Proto_2fGetMouselogCommandResponse_2eproto();
void protobuf_AssignDesc_Proto_2fGetMouselogCommandResponse_2eproto();
void protobuf_ShutdownFile_Proto_2fGetMouselogCommandResponse_2eproto();

class GetMouselogCommandResponse;

// ===================================================================

class GetMouselogCommandResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetMouselogCommandResponse) */ {
 public:
  GetMouselogCommandResponse();
  virtual ~GetMouselogCommandResponse();

  GetMouselogCommandResponse(const GetMouselogCommandResponse& from);

  inline GetMouselogCommandResponse& operator=(const GetMouselogCommandResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetMouselogCommandResponse& default_instance();

  static const GetMouselogCommandResponse* internal_default_instance();

  void Swap(GetMouselogCommandResponse* other);

  // implements Message ----------------------------------------------

  inline GetMouselogCommandResponse* New() const { return New(NULL); }

  GetMouselogCommandResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetMouselogCommandResponse& from);
  void MergeFrom(const GetMouselogCommandResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetMouselogCommandResponse* other);
  void UnsafeMergeFrom(const GetMouselogCommandResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SpiderMouseEvent keylog = 1;
  int keylog_size() const;
  void clear_keylog();
  static const int kKeylogFieldNumber = 1;
  const ::SpiderMouseEvent& keylog(int index) const;
  ::SpiderMouseEvent* mutable_keylog(int index);
  ::SpiderMouseEvent* add_keylog();
  ::google::protobuf::RepeatedPtrField< ::SpiderMouseEvent >*
      mutable_keylog();
  const ::google::protobuf::RepeatedPtrField< ::SpiderMouseEvent >&
      keylog() const;

  // @@protoc_insertion_point(class_scope:GetMouselogCommandResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::SpiderMouseEvent > keylog_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fGetMouselogCommandResponse_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fGetMouselogCommandResponse_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fGetMouselogCommandResponse_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fGetMouselogCommandResponse_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetMouselogCommandResponse> GetMouselogCommandResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetMouselogCommandResponse

// repeated .SpiderMouseEvent keylog = 1;
inline int GetMouselogCommandResponse::keylog_size() const {
  return keylog_.size();
}
inline void GetMouselogCommandResponse::clear_keylog() {
  keylog_.Clear();
}
inline const ::SpiderMouseEvent& GetMouselogCommandResponse::keylog(int index) const {
  // @@protoc_insertion_point(field_get:GetMouselogCommandResponse.keylog)
  return keylog_.Get(index);
}
inline ::SpiderMouseEvent* GetMouselogCommandResponse::mutable_keylog(int index) {
  // @@protoc_insertion_point(field_mutable:GetMouselogCommandResponse.keylog)
  return keylog_.Mutable(index);
}
inline ::SpiderMouseEvent* GetMouselogCommandResponse::add_keylog() {
  // @@protoc_insertion_point(field_add:GetMouselogCommandResponse.keylog)
  return keylog_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::SpiderMouseEvent >*
GetMouselogCommandResponse::mutable_keylog() {
  // @@protoc_insertion_point(field_mutable_list:GetMouselogCommandResponse.keylog)
  return &keylog_;
}
inline const ::google::protobuf::RepeatedPtrField< ::SpiderMouseEvent >&
GetMouselogCommandResponse::keylog() const {
  // @@protoc_insertion_point(field_list:GetMouselogCommandResponse.keylog)
  return keylog_;
}

inline const GetMouselogCommandResponse* GetMouselogCommandResponse::internal_default_instance() {
  return &GetMouselogCommandResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_2fGetMouselogCommandResponse_2eproto__INCLUDED
