// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/ListUUIDSCommandResponse.proto

#ifndef PROTOBUF_Proto_2fListUUIDSCommandResponse_2eproto__INCLUDED
#define PROTOBUF_Proto_2fListUUIDSCommandResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Proto_2fListUUIDSCommandResponse_2eproto();
void protobuf_InitDefaults_Proto_2fListUUIDSCommandResponse_2eproto();
void protobuf_AssignDesc_Proto_2fListUUIDSCommandResponse_2eproto();
void protobuf_ShutdownFile_Proto_2fListUUIDSCommandResponse_2eproto();

class ListUUIDSCommandResponse;

// ===================================================================

class ListUUIDSCommandResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ListUUIDSCommandResponse) */ {
 public:
  ListUUIDSCommandResponse();
  virtual ~ListUUIDSCommandResponse();

  ListUUIDSCommandResponse(const ListUUIDSCommandResponse& from);

  inline ListUUIDSCommandResponse& operator=(const ListUUIDSCommandResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListUUIDSCommandResponse& default_instance();

  static const ListUUIDSCommandResponse* internal_default_instance();

  void Swap(ListUUIDSCommandResponse* other);

  // implements Message ----------------------------------------------

  inline ListUUIDSCommandResponse* New() const { return New(NULL); }

  ListUUIDSCommandResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListUUIDSCommandResponse& from);
  void MergeFrom(const ListUUIDSCommandResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListUUIDSCommandResponse* other);
  void UnsafeMergeFrom(const ListUUIDSCommandResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string uuid = 1;
  int uuid_size() const;
  void clear_uuid();
  static const int kUuidFieldNumber = 1;
  const ::std::string& uuid(int index) const;
  ::std::string* mutable_uuid(int index);
  void set_uuid(int index, const ::std::string& value);
  void set_uuid(int index, const char* value);
  void set_uuid(int index, const char* value, size_t size);
  ::std::string* add_uuid();
  void add_uuid(const ::std::string& value);
  void add_uuid(const char* value);
  void add_uuid(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& uuid() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_uuid();

  // @@protoc_insertion_point(class_scope:ListUUIDSCommandResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> uuid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Proto_2fListUUIDSCommandResponse_2eproto_impl();
  friend void  protobuf_AddDesc_Proto_2fListUUIDSCommandResponse_2eproto_impl();
  friend void protobuf_AssignDesc_Proto_2fListUUIDSCommandResponse_2eproto();
  friend void protobuf_ShutdownFile_Proto_2fListUUIDSCommandResponse_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ListUUIDSCommandResponse> ListUUIDSCommandResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ListUUIDSCommandResponse

// repeated string uuid = 1;
inline int ListUUIDSCommandResponse::uuid_size() const {
  return uuid_.size();
}
inline void ListUUIDSCommandResponse::clear_uuid() {
  uuid_.Clear();
}
inline const ::std::string& ListUUIDSCommandResponse::uuid(int index) const {
  // @@protoc_insertion_point(field_get:ListUUIDSCommandResponse.uuid)
  return uuid_.Get(index);
}
inline ::std::string* ListUUIDSCommandResponse::mutable_uuid(int index) {
  // @@protoc_insertion_point(field_mutable:ListUUIDSCommandResponse.uuid)
  return uuid_.Mutable(index);
}
inline void ListUUIDSCommandResponse::set_uuid(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ListUUIDSCommandResponse.uuid)
  uuid_.Mutable(index)->assign(value);
}
inline void ListUUIDSCommandResponse::set_uuid(int index, const char* value) {
  uuid_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ListUUIDSCommandResponse.uuid)
}
inline void ListUUIDSCommandResponse::set_uuid(int index, const char* value, size_t size) {
  uuid_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ListUUIDSCommandResponse.uuid)
}
inline ::std::string* ListUUIDSCommandResponse::add_uuid() {
  // @@protoc_insertion_point(field_add_mutable:ListUUIDSCommandResponse.uuid)
  return uuid_.Add();
}
inline void ListUUIDSCommandResponse::add_uuid(const ::std::string& value) {
  uuid_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ListUUIDSCommandResponse.uuid)
}
inline void ListUUIDSCommandResponse::add_uuid(const char* value) {
  uuid_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ListUUIDSCommandResponse.uuid)
}
inline void ListUUIDSCommandResponse::add_uuid(const char* value, size_t size) {
  uuid_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ListUUIDSCommandResponse.uuid)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListUUIDSCommandResponse::uuid() const {
  // @@protoc_insertion_point(field_list:ListUUIDSCommandResponse.uuid)
  return uuid_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListUUIDSCommandResponse::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable_list:ListUUIDSCommandResponse.uuid)
  return &uuid_;
}

inline const ListUUIDSCommandResponse* ListUUIDSCommandResponse::internal_default_instance() {
  return &ListUUIDSCommandResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_2fListUUIDSCommandResponse_2eproto__INCLUDED
