// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpiderEnvelop.proto

#ifndef PROTOBUF_SpiderEnvelop_2eproto__INCLUDED
#define PROTOBUF_SpiderEnvelop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_SpiderEnvelop_2eproto();
void protobuf_AssignDesc_SpiderEnvelop_2eproto();
void protobuf_ShutdownFile_SpiderEnvelop_2eproto();

class SpiderEnveloppe;

// ===================================================================

class SpiderEnveloppe : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SpiderEnveloppe) */ {
 public:
  SpiderEnveloppe();
  virtual ~SpiderEnveloppe();

  SpiderEnveloppe(const SpiderEnveloppe& from);

  inline SpiderEnveloppe& operator=(const SpiderEnveloppe& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpiderEnveloppe& default_instance();

  void Swap(SpiderEnveloppe* other);

  // implements Message ----------------------------------------------

  inline SpiderEnveloppe* New() const { return New(NULL); }

  SpiderEnveloppe* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpiderEnveloppe& from);
  void MergeFrom(const SpiderEnveloppe& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SpiderEnveloppe* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string ClientID = 1;
  void clear_clientid();
  static const int kClientIDFieldNumber = 1;
  const ::std::string& clientid() const;
  void set_clientid(const ::std::string& value);
  void set_clientid(const char* value);
  void set_clientid(const char* value, size_t size);
  ::std::string* mutable_clientid();
  ::std::string* release_clientid();
  void set_allocated_clientid(::std::string* clientid);

  // optional string PayloadType = 2;
  void clear_payloadtype();
  static const int kPayloadTypeFieldNumber = 2;
  const ::std::string& payloadtype() const;
  void set_payloadtype(const ::std::string& value);
  void set_payloadtype(const char* value);
  void set_payloadtype(const char* value, size_t size);
  ::std::string* mutable_payloadtype();
  ::std::string* release_payloadtype();
  void set_allocated_payloadtype(::std::string* payloadtype);

  // optional .google.protobuf.Any Payload = 3;
  bool has_payload() const;
  void clear_payload();
  static const int kPayloadFieldNumber = 3;
  const ::google::protobuf::Any& payload() const;
  ::google::protobuf::Any* mutable_payload();
  ::google::protobuf::Any* release_payload();
  void set_allocated_payload(::google::protobuf::Any* payload);

  // @@protoc_insertion_point(class_scope:SpiderEnveloppe)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr clientid_;
  ::google::protobuf::internal::ArenaStringPtr payloadtype_;
  ::google::protobuf::Any* payload_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_SpiderEnvelop_2eproto();
  friend void protobuf_AssignDesc_SpiderEnvelop_2eproto();
  friend void protobuf_ShutdownFile_SpiderEnvelop_2eproto();

  void InitAsDefaultInstance();
  static SpiderEnveloppe* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SpiderEnveloppe

// optional string ClientID = 1;
inline void SpiderEnveloppe::clear_clientid() {
  clientid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SpiderEnveloppe::clientid() const {
  // @@protoc_insertion_point(field_get:SpiderEnveloppe.ClientID)
  return clientid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpiderEnveloppe::set_clientid(const ::std::string& value) {
  
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SpiderEnveloppe.ClientID)
}
inline void SpiderEnveloppe::set_clientid(const char* value) {
  
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SpiderEnveloppe.ClientID)
}
inline void SpiderEnveloppe::set_clientid(const char* value, size_t size) {
  
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SpiderEnveloppe.ClientID)
}
inline ::std::string* SpiderEnveloppe::mutable_clientid() {
  
  // @@protoc_insertion_point(field_mutable:SpiderEnveloppe.ClientID)
  return clientid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpiderEnveloppe::release_clientid() {
  // @@protoc_insertion_point(field_release:SpiderEnveloppe.ClientID)
  
  return clientid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpiderEnveloppe::set_allocated_clientid(::std::string* clientid) {
  if (clientid != NULL) {
    
  } else {
    
  }
  clientid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clientid);
  // @@protoc_insertion_point(field_set_allocated:SpiderEnveloppe.ClientID)
}

// optional string PayloadType = 2;
inline void SpiderEnveloppe::clear_payloadtype() {
  payloadtype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SpiderEnveloppe::payloadtype() const {
  // @@protoc_insertion_point(field_get:SpiderEnveloppe.PayloadType)
  return payloadtype_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpiderEnveloppe::set_payloadtype(const ::std::string& value) {
  
  payloadtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SpiderEnveloppe.PayloadType)
}
inline void SpiderEnveloppe::set_payloadtype(const char* value) {
  
  payloadtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SpiderEnveloppe.PayloadType)
}
inline void SpiderEnveloppe::set_payloadtype(const char* value, size_t size) {
  
  payloadtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SpiderEnveloppe.PayloadType)
}
inline ::std::string* SpiderEnveloppe::mutable_payloadtype() {
  
  // @@protoc_insertion_point(field_mutable:SpiderEnveloppe.PayloadType)
  return payloadtype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpiderEnveloppe::release_payloadtype() {
  // @@protoc_insertion_point(field_release:SpiderEnveloppe.PayloadType)
  
  return payloadtype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpiderEnveloppe::set_allocated_payloadtype(::std::string* payloadtype) {
  if (payloadtype != NULL) {
    
  } else {
    
  }
  payloadtype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payloadtype);
  // @@protoc_insertion_point(field_set_allocated:SpiderEnveloppe.PayloadType)
}

// optional .google.protobuf.Any Payload = 3;
inline bool SpiderEnveloppe::has_payload() const {
  return !_is_default_instance_ && payload_ != NULL;
}
inline void SpiderEnveloppe::clear_payload() {
  if (GetArenaNoVirtual() == NULL && payload_ != NULL) delete payload_;
  payload_ = NULL;
}
inline const ::google::protobuf::Any& SpiderEnveloppe::payload() const {
  // @@protoc_insertion_point(field_get:SpiderEnveloppe.Payload)
  return payload_ != NULL ? *payload_ : *default_instance_->payload_;
}
inline ::google::protobuf::Any* SpiderEnveloppe::mutable_payload() {
  
  if (payload_ == NULL) {
    payload_ = new ::google::protobuf::Any;
  }
  // @@protoc_insertion_point(field_mutable:SpiderEnveloppe.Payload)
  return payload_;
}
inline ::google::protobuf::Any* SpiderEnveloppe::release_payload() {
  // @@protoc_insertion_point(field_release:SpiderEnveloppe.Payload)
  
  ::google::protobuf::Any* temp = payload_;
  payload_ = NULL;
  return temp;
}
inline void SpiderEnveloppe::set_allocated_payload(::google::protobuf::Any* payload) {
  delete payload_;
  payload_ = payload;
  if (payload) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SpiderEnveloppe.Payload)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SpiderEnvelop_2eproto__INCLUDED
