//
// Created by etiennep on 11/8/16.
//

#ifndef SPIDER_CLIENT_ISPIDERMESSAGEDESERIALIZER_HPP
#define SPIDER_CLIENT_ISPIDERMESSAGEDESERIALIZER_HPP

class ISpiderMessageDeserializer {
public:
};

#endif //SPIDER_CLIENT_ISPIDERMESSAGEDESERIALIZER_HPP