#ifndef SPIDER_SERVER_ISPIDEREVENTMANAGER_HPP
#define SPIDER_SERVER_ISPIDEREVENTMANAGER_HPP

class ISpiderEventManager {
public:
	virtual void Run() = 0;
};

#endif //SPIDER_SERVER_ISPIDEREVENTMANAGER_HPP