//
// Created by etiennep on 11/8/16.
//

#ifndef SPIDER_CLIENT_ISPIDERCOMMANDHANDLER_HPP
#define SPIDER_CLIENT_ISPIDERCOMMANDHANDLER_HPP

class ISpiderCommandHandler {
public:
};

#endif //SPIDER_CLIENT_ISPIDERCOMMANDHANDLER_HPP