//
// Created by etiennep on 11/8/16.
//

#ifndef SPIDER_CLIENT_IWINDOWSCONTEXTAGENT_HPP
#define SPIDER_CLIENT_IWINDOWSCONTEXTAGENT_HPP

class IWindowsContextAgent {
public:
};

#endif //SPIDER_CLIENT_IWINDOWSCONTEXTAGENT_HPP