// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/SpiderContextChangedEvent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SpiderContextChangedEvent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SpiderContextChangedEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpiderContextChangedEvent_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Proto_2fSpiderContextChangedEvent_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Proto_2fSpiderContextChangedEvent_2eproto() {
  protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Proto/SpiderContextChangedEvent.proto");
  GOOGLE_CHECK(file != NULL);
  SpiderContextChangedEvent_descriptor_ = file->message_type(0);
  static const int SpiderContextChangedEvent_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpiderContextChangedEvent, processname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpiderContextChangedEvent, windowtitle_),
  };
  SpiderContextChangedEvent_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SpiderContextChangedEvent_descriptor_,
      SpiderContextChangedEvent::internal_default_instance(),
      SpiderContextChangedEvent_offsets_,
      -1,
      -1,
      -1,
      sizeof(SpiderContextChangedEvent),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpiderContextChangedEvent, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Proto_2fSpiderContextChangedEvent_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SpiderContextChangedEvent_descriptor_, SpiderContextChangedEvent::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Proto_2fSpiderContextChangedEvent_2eproto() {
  SpiderContextChangedEvent_default_instance_.Shutdown();
  delete SpiderContextChangedEvent_reflection_;
}

void protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  SpiderContextChangedEvent_default_instance_.DefaultConstruct();
  SpiderContextChangedEvent_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto_once_);
void protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto_once_,
                 &protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto_impl);
}
void protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n%Proto/SpiderContextChangedEvent.proto\""
    "E\n\031SpiderContextChangedEvent\022\023\n\013ProcessN"
    "ame\030\001 \001(\t\022\023\n\013WindowTitle\030\002 \001(\tb\006proto3", 118);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Proto/SpiderContextChangedEvent.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Proto_2fSpiderContextChangedEvent_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto_once_);
void protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto_once_,
                 &protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Proto_2fSpiderContextChangedEvent_2eproto {
  StaticDescriptorInitializer_Proto_2fSpiderContextChangedEvent_2eproto() {
    protobuf_AddDesc_Proto_2fSpiderContextChangedEvent_2eproto();
  }
} static_descriptor_initializer_Proto_2fSpiderContextChangedEvent_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpiderContextChangedEvent::kProcessNameFieldNumber;
const int SpiderContextChangedEvent::kWindowTitleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpiderContextChangedEvent::SpiderContextChangedEvent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:SpiderContextChangedEvent)
}

void SpiderContextChangedEvent::InitAsDefaultInstance() {
}

SpiderContextChangedEvent::SpiderContextChangedEvent(const SpiderContextChangedEvent& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SpiderContextChangedEvent)
}

void SpiderContextChangedEvent::SharedCtor() {
  processname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  windowtitle_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

SpiderContextChangedEvent::~SpiderContextChangedEvent() {
  // @@protoc_insertion_point(destructor:SpiderContextChangedEvent)
  SharedDtor();
}

void SpiderContextChangedEvent::SharedDtor() {
  processname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  windowtitle_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SpiderContextChangedEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpiderContextChangedEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpiderContextChangedEvent_descriptor_;
}

const SpiderContextChangedEvent& SpiderContextChangedEvent::default_instance() {
  protobuf_InitDefaults_Proto_2fSpiderContextChangedEvent_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SpiderContextChangedEvent> SpiderContextChangedEvent_default_instance_;

SpiderContextChangedEvent* SpiderContextChangedEvent::New(::google::protobuf::Arena* arena) const {
  SpiderContextChangedEvent* n = new SpiderContextChangedEvent;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SpiderContextChangedEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:SpiderContextChangedEvent)
  processname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  windowtitle_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool SpiderContextChangedEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SpiderContextChangedEvent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string ProcessName = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_processname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->processname().data(), this->processname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "SpiderContextChangedEvent.ProcessName"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_WindowTitle;
        break;
      }

      // optional string WindowTitle = 2;
      case 2: {
        if (tag == 18) {
         parse_WindowTitle:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_windowtitle()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->windowtitle().data(), this->windowtitle().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "SpiderContextChangedEvent.WindowTitle"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SpiderContextChangedEvent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SpiderContextChangedEvent)
  return false;
#undef DO_
}

void SpiderContextChangedEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SpiderContextChangedEvent)
  // optional string ProcessName = 1;
  if (this->processname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->processname().data(), this->processname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "SpiderContextChangedEvent.ProcessName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->processname(), output);
  }

  // optional string WindowTitle = 2;
  if (this->windowtitle().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->windowtitle().data(), this->windowtitle().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "SpiderContextChangedEvent.WindowTitle");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->windowtitle(), output);
  }

  // @@protoc_insertion_point(serialize_end:SpiderContextChangedEvent)
}

::google::protobuf::uint8* SpiderContextChangedEvent::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:SpiderContextChangedEvent)
  // optional string ProcessName = 1;
  if (this->processname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->processname().data(), this->processname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "SpiderContextChangedEvent.ProcessName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->processname(), target);
  }

  // optional string WindowTitle = 2;
  if (this->windowtitle().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->windowtitle().data(), this->windowtitle().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "SpiderContextChangedEvent.WindowTitle");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->windowtitle(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SpiderContextChangedEvent)
  return target;
}

size_t SpiderContextChangedEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SpiderContextChangedEvent)
  size_t total_size = 0;

  // optional string ProcessName = 1;
  if (this->processname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->processname());
  }

  // optional string WindowTitle = 2;
  if (this->windowtitle().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->windowtitle());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpiderContextChangedEvent::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SpiderContextChangedEvent)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SpiderContextChangedEvent* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpiderContextChangedEvent>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SpiderContextChangedEvent)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SpiderContextChangedEvent)
    UnsafeMergeFrom(*source);
  }
}

void SpiderContextChangedEvent::MergeFrom(const SpiderContextChangedEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SpiderContextChangedEvent)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void SpiderContextChangedEvent::UnsafeMergeFrom(const SpiderContextChangedEvent& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.processname().size() > 0) {

    processname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.processname_);
  }
  if (from.windowtitle().size() > 0) {

    windowtitle_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.windowtitle_);
  }
}

void SpiderContextChangedEvent::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SpiderContextChangedEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpiderContextChangedEvent::CopyFrom(const SpiderContextChangedEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SpiderContextChangedEvent)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool SpiderContextChangedEvent::IsInitialized() const {

  return true;
}

void SpiderContextChangedEvent::Swap(SpiderContextChangedEvent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpiderContextChangedEvent::InternalSwap(SpiderContextChangedEvent* other) {
  processname_.Swap(&other->processname_);
  windowtitle_.Swap(&other->windowtitle_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SpiderContextChangedEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpiderContextChangedEvent_descriptor_;
  metadata.reflection = SpiderContextChangedEvent_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SpiderContextChangedEvent

// optional string ProcessName = 1;
void SpiderContextChangedEvent::clear_processname() {
  processname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SpiderContextChangedEvent::processname() const {
  // @@protoc_insertion_point(field_get:SpiderContextChangedEvent.ProcessName)
  return processname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SpiderContextChangedEvent::set_processname(const ::std::string& value) {
  
  processname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SpiderContextChangedEvent.ProcessName)
}
void SpiderContextChangedEvent::set_processname(const char* value) {
  
  processname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SpiderContextChangedEvent.ProcessName)
}
void SpiderContextChangedEvent::set_processname(const char* value, size_t size) {
  
  processname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SpiderContextChangedEvent.ProcessName)
}
::std::string* SpiderContextChangedEvent::mutable_processname() {
  
  // @@protoc_insertion_point(field_mutable:SpiderContextChangedEvent.ProcessName)
  return processname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SpiderContextChangedEvent::release_processname() {
  // @@protoc_insertion_point(field_release:SpiderContextChangedEvent.ProcessName)
  
  return processname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SpiderContextChangedEvent::set_allocated_processname(::std::string* processname) {
  if (processname != NULL) {
    
  } else {
    
  }
  processname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), processname);
  // @@protoc_insertion_point(field_set_allocated:SpiderContextChangedEvent.ProcessName)
}

// optional string WindowTitle = 2;
void SpiderContextChangedEvent::clear_windowtitle() {
  windowtitle_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SpiderContextChangedEvent::windowtitle() const {
  // @@protoc_insertion_point(field_get:SpiderContextChangedEvent.WindowTitle)
  return windowtitle_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SpiderContextChangedEvent::set_windowtitle(const ::std::string& value) {
  
  windowtitle_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SpiderContextChangedEvent.WindowTitle)
}
void SpiderContextChangedEvent::set_windowtitle(const char* value) {
  
  windowtitle_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SpiderContextChangedEvent.WindowTitle)
}
void SpiderContextChangedEvent::set_windowtitle(const char* value, size_t size) {
  
  windowtitle_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SpiderContextChangedEvent.WindowTitle)
}
::std::string* SpiderContextChangedEvent::mutable_windowtitle() {
  
  // @@protoc_insertion_point(field_mutable:SpiderContextChangedEvent.WindowTitle)
  return windowtitle_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SpiderContextChangedEvent::release_windowtitle() {
  // @@protoc_insertion_point(field_release:SpiderContextChangedEvent.WindowTitle)
  
  return windowtitle_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SpiderContextChangedEvent::set_allocated_windowtitle(::std::string* windowtitle) {
  if (windowtitle != NULL) {
    
  } else {
    
  }
  windowtitle_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), windowtitle);
  // @@protoc_insertion_point(field_set_allocated:SpiderContextChangedEvent.WindowTitle)
}

inline const SpiderContextChangedEvent* SpiderContextChangedEvent::internal_default_instance() {
  return &SpiderContextChangedEvent_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
