// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* testPayload_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  testPayload_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Proto_2ftest_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Proto_2ftest_2eproto() {
  protobuf_AddDesc_Proto_2ftest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Proto/test.proto");
  GOOGLE_CHECK(file != NULL);
  testPayload_descriptor_ = file->message_type(0);
  static const int testPayload_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testPayload, content_),
  };
  testPayload_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      testPayload_descriptor_,
      testPayload::internal_default_instance(),
      testPayload_offsets_,
      -1,
      -1,
      -1,
      sizeof(testPayload),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testPayload, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Proto_2ftest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      testPayload_descriptor_, testPayload::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Proto_2ftest_2eproto() {
  testPayload_default_instance_.Shutdown();
  delete testPayload_reflection_;
}

void protobuf_InitDefaults_Proto_2ftest_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  testPayload_default_instance_.DefaultConstruct();
  testPayload_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_Proto_2ftest_2eproto_once_);
void protobuf_InitDefaults_Proto_2ftest_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_Proto_2ftest_2eproto_once_,
                 &protobuf_InitDefaults_Proto_2ftest_2eproto_impl);
}
void protobuf_AddDesc_Proto_2ftest_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_Proto_2ftest_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020Proto/test.proto\"\036\n\013testPayload\022\017\n\007con"
    "tent\030\001 \001(\tb\006proto3", 58);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Proto/test.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Proto_2ftest_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_Proto_2ftest_2eproto_once_);
void protobuf_AddDesc_Proto_2ftest_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_Proto_2ftest_2eproto_once_,
                 &protobuf_AddDesc_Proto_2ftest_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Proto_2ftest_2eproto {
  StaticDescriptorInitializer_Proto_2ftest_2eproto() {
    protobuf_AddDesc_Proto_2ftest_2eproto();
  }
} static_descriptor_initializer_Proto_2ftest_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int testPayload::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

testPayload::testPayload()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Proto_2ftest_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:testPayload)
}

void testPayload::InitAsDefaultInstance() {
}

testPayload::testPayload(const testPayload& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:testPayload)
}

void testPayload::SharedCtor() {
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

testPayload::~testPayload() {
  // @@protoc_insertion_point(destructor:testPayload)
  SharedDtor();
}

void testPayload::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void testPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* testPayload::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return testPayload_descriptor_;
}

const testPayload& testPayload::default_instance() {
  protobuf_InitDefaults_Proto_2ftest_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<testPayload> testPayload_default_instance_;

testPayload* testPayload::New(::google::protobuf::Arena* arena) const {
  testPayload* n = new testPayload;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void testPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:testPayload)
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool testPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:testPayload)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string content = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), this->content().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "testPayload.content"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:testPayload)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:testPayload)
  return false;
#undef DO_
}

void testPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:testPayload)
  // optional string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPayload.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content(), output);
  }

  // @@protoc_insertion_point(serialize_end:testPayload)
}

::google::protobuf::uint8* testPayload::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:testPayload)
  // optional string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPayload.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:testPayload)
  return target;
}

size_t testPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:testPayload)
  size_t total_size = 0;

  // optional string content = 1;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void testPayload::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:testPayload)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const testPayload* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const testPayload>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:testPayload)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:testPayload)
    UnsafeMergeFrom(*source);
  }
}

void testPayload::MergeFrom(const testPayload& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:testPayload)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void testPayload::UnsafeMergeFrom(const testPayload& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
}

void testPayload::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:testPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void testPayload::CopyFrom(const testPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:testPayload)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool testPayload::IsInitialized() const {

  return true;
}

void testPayload::Swap(testPayload* other) {
  if (other == this) return;
  InternalSwap(other);
}
void testPayload::InternalSwap(testPayload* other) {
  content_.Swap(&other->content_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata testPayload::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = testPayload_descriptor_;
  metadata.reflection = testPayload_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// testPayload

// optional string content = 1;
void testPayload::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& testPayload::content() const {
  // @@protoc_insertion_point(field_get:testPayload.content)
  return content_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void testPayload::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:testPayload.content)
}
void testPayload::set_content(const char* value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:testPayload.content)
}
void testPayload::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:testPayload.content)
}
::std::string* testPayload::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:testPayload.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* testPayload::release_content() {
  // @@protoc_insertion_point(field_release:testPayload.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void testPayload::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:testPayload.content)
}

inline const testPayload* testPayload::internal_default_instance() {
  return &testPayload_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
